= CORE Platform from Moonlight Labs

== CONTENTS

* .prettier.yml - `npx prettier -c .` or `npx prettier -w` to check or format many code files
* .rubocop.yml - `rubocopy -a` to cleanup and report on ruby code
* Taskfile.yml - `task` to see tasks that can run across full repo

== SETUP for Core-Accounting
* add the core gems to your Gemfile
```
git 'https://github.com/moonlight-labs/core.git', branch: 'main' do
  gem 'core-base'
  gem 'core-accounting'
end
```
* run `bundle`
* run `rails db:migrate`
* include `include Core::Accounting::GraphQL::Queries` in `Types::Query`. ex:
```
class Types::Query < GraphQL::Schema::Object
  include Core::Accounting::GraphQL::Queries
end
```
* add a core-accounting initializer to 
- configure double entry
- define double entry accounts
- define double entry transfers
- extend the DoubleEntry::Line model (particularly for configuring the metadata jsonb_accessor)
- extend the Core::Accounting::GraphQL::Types::Line 

== SETUP for Core-Accounting-FE
* add core-accounting-fe pkg `yarn add https://gitpkg.now.sh/moonlight-labs/core/core-accounting-fe?main`
* ensure peer dependencies are installed
* add Jobs RA Resource (which can be customized as shown below)
```
const AccountScopeReferenceField: React.FC<{source: string}> = ({source}) => {
  const record = useRecordContext()
  if (!record) return null
  return (
    <ReferenceField
      label="Scope"
      reference={record.scopeDetail.model}
      source="scopeDetail.id"
    >
      <TextField source="name" />
    </ReferenceField>
  )
}

<Resource 
  key="admin-lines-resource"
  name="line"
  options={[{ label: 'Ledger Lines', menu: 'admin' }]}
  show={<CoreAccounting.Lines.Show />}
  list={
    <CoreAccounting.Lines.List
    tableProps={{filters: lineFilters}}
    >
      <TextField label="Account" source="accountIdentifier" sortable={false} />
      <AccountScopeReferenceField source="Scope" />
      <TextField source="scope" sortable={false} />
    </CoreAccounting.Lines.List>
  }
/>
```

== SETUP for Core-Jobs
* add the core gems to your Gemfile
```
git 'https://github.com/moonlight-labs/core.git', branch: 'main' do
  gem 'core-base'
  gem 'core-jobs'
end
```
* run `bundle`
* run `rails db:migrate`
* set `config.active_job.queue_adapter = :que` in `(environment).rb`
* include `include Core::Jobs::GraphQL::Queries` in `Types::Query`. ex:
```
class Types::Query < GraphQL::Schema::Object
  include Core::Jobs::GraphQL::Queries
end
```
* include `include Core::Jobs::GraphQL::Mutations` in `Types::Mutation`. ex:
```
class Types::Mutation < GraphQL::Schema::Object
  include Core::Jobs::GraphQL::Mutations
end
```
* configure the job runner (in Procfile, etc.)
```
worker: bin/que ./config/environment.rb -q high -q default -q low
worker-low: bin/que ./config/environment.rb -q low
worker-high: bin/que ./config/environment.rb -q high
```
* configure workers within puma config
```
# w/in config/puma.rb
plugin :que
```

== SETUP for Core-Jobs-FE
* add core-jobs-fe pkg `yarn add https://gitpkg.now.sh/moonlight-labs/core/core-jobs-fe?main`
* ensure peer dependencies are installed
* add Jobs RA Resource
```
<Resource
  key="admin-jobs-resource"
  name="admin/job"
  icon={DashboardIcon}
  options={[{ label: 'Job Queue', menu: 'admin' }]}
  edit={<CoreJobs.Resource.Edit />}
  list={<CoreJobs.Resource.List />}
/>
```

== SETUP for Core-Comments
* add the core gems to your Gemfile
```
git 'https://github.com/moonlight-labs/core.git', branch: 'main' do
  gem 'core-base'
  gem 'core-comments'
end
```
* run `bundle`
* run `rails db:migrate`
* include `include Core::Comments::GraphQL::Queries` in `Types::Query`. ex:
```
class Types::Query < GraphQL::Schema::Object
  include Core::Comments::GraphQL::Queries
end
```
* include `include Core::Comments::GraphQL::Mutations` in `Types::Mutation`. ex:
```
class Types::Mutation < GraphQL::Schema::Object
  include Core::Comments::GraphQL::Mutations
end
```

== SETUP for Core-Comments-FE
* add core-comments-fe pkg `yarn add https://gitpkg.now.sh/moonlight-labs/core/core-comments-fe?main`
* ensure peer dependencies are installed
* add Comments RA Resource
```
<Resource
  key="admin-comments-resource"
  name="Comment"
  options={[{ label: 'Comments', menu: 'admin' }]}
  list={<CoreComments.Comments.List />}
  edit={<CoreComments.Comments.Edit />}
/>
```

== SETUP for Core-Versions
* add the core gems to your Gemfile
```
git 'https://github.com/moonlight-labs/core.git', branch: 'main' do
  gem 'core-base'
  gem 'core-versions'
end
```
* run `bundle`
* run `rails db:migrate`
* include `include Core::Versions::GraphQL::Queries` in `Types::Query`. ex:
```
class Types::Query < GraphQL::Schema::Object
  include Core::Versions::GraphQL::Queries
end
```
* add `before_action :set_core_versions_actor` to your `ApplicationController` or other wanted controllers
* add `has_core_versions` to any wanted models (this supports options passed in for what to monitor the same as https://github.com/paper-trail-gem/paper_trail#2c-choosing-attributes-to-monitor[PaperTrail])

== SETUP for Core-Versions-FE
* add core-versions-fe pkg `yarn add https://gitpkg.now.sh/moonlight-labs/core/core-versions-fe?main`
* ensure peer dependencies are installed
* add Versions RA Resource
```
<Resource
  key="admin-versions-resource"
  name="Version"
  options={[{ label: 'Versions', menu: 'admin' }]}
  list={<CoreVersions.Versions.List />}
  show={<CoreVersions.Versions.Show />}
/>
```

== SETUP for Core-Referrals
* add the core gems to your Gemfile
```
git 'https://github.com/moonlight-labs/core.git', branch: 'main' do
  gem 'core-base'
  gem 'core-referrals'
end
```
* run `bundle`
* run `rails db:migrate`
* add `include Core::Referrals::HasCoreReferrals` to any wanted models
* those models will now have access to:
```
.referral_codes # that record's list of referral codes
.referrals # that record's list of referrals from referral codes
.ensure_referral_code! # find or create a referral code record
.create_referral!(referred) # create a new referral from that record for the referred (will create a code if needed)
```
* if needed, the default behavior of referral code generation can be overridden by overriding the `generate_code` method in the `Referrer` model

== SAMPLES

* core-rails6-sample-app - created with `rails _6.1.6_ new core-rails6-sample-app -d=postgresql -J --skip-turbolinks`

== TODO

- [ ] Setup CLOC ie `cloc --vcs=git`
- [ ] Code coverage

== See also
* Combustion - simpler dummy apps for testing modules
https://github.com/pat/combustion

* How to use Railtie initialization in Sinatra apps
https://marceloreichert.medium.com/using-rolify-with-sinatra-ad6d876ef669
