# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in core-jobs.gemspec
gemspec

# group :test do
#   gem 'activerecord'
# end

# gem 'minitest', '~> 5.0'
# gem 'rake', '~> 12.0'
