# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in core-jobs.gemspec
gemspec

group :test do
  gem 'activerecord'
  gem 'papertrail'
end

gem 'minitest'
gem 'rake'
