# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in groovestack-identities.gemspec
gemspec

group :test do
  gem 'fabrication'
  gem 'faker'
  gem 'rails'
  gem 'rspec'
  gem 'wisper'
end

gem 'rake', '~> 12.0'
gem 'rubocop'
gem 'rubocop-graphql', '~> 1.0'
gem 'rubocop-rails', '~> 2.18'