# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in groovestack-base.gemspec
gemspec

group :test do
  gem 'rails'
  gem 'rspec'
  gem 'wisper'
end
gem 'puma', '~> 6'
gem 'rake', '~> 12.0'
gem 'rubocop'
gem 'rubocop-graphql', '~> 1.0'
gem 'rubocop-rails', '~> 2.18'
