# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in groovestack-base.gemspec
gemspec

group :test do
  gem 'rails'
  gem 'rspec'
  gem 'wisper'
end
gem 'rake', '~> 12.0'
gem 'rubocop', require: false
