# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in groovestack-config.gemspec
gemspec

gem 'rake', '~> 13.0'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-graphql', '~> 1.0'
gem 'rubocop-rails', '~> 2.18'
