# frozen_string_literal: true

source 'https://rubygems.org'

git 'https://github.com/moonlight-labs/core.git', branch: 'core-accounting' do
  gem 'core-graphql'
end

# Specify your gem's dependencies in core-jobs.gemspec
gemspec

group :test do
  gem 'activerecord'
end

gem 'minitest', '~> 5.0'
gem 'rake', '~> 12.0'
