require:
  - rubocop-graphql
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.3

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

Layout/LineLength:
  Exclude:
    - spec/**/*

# TODO: re-evaluate
Lint/ConstantDefinitionInBlock:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - '*.gemspec'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false



# Style/StringLiterals:
#   Enabled: true
#   EnforcedStyle: double_quotes

# Style/StringLiteralsInInterpolation:
#   Enabled: true
#   EnforcedStyle: double_quotes

# Layout/LineLength:
#   Max: 120
