# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in groovestack-auth.gemspec
gemspec

gem 'fabrication'
gem 'faker'
gem 'racksh' # get a console without a full Rails application
gem 'rspec'
gem 'rubocop', require: false
